[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Jiyu <hello@jiyu.sh>"]
edition = "2024"
rust-version = "1.99"
repository = "https://github.com/jiyu-sh/jiyu"
license = "MIT"

[workspace.dependencies.anyhow]
version = "1.0.104"
default-features = false

[workspace.dependencies.bon]
version = "3.10.2"
default-features = false

[workspace.dependencies.capnp]
version = "0.27.2"
default-features = false

[workspace.dependencies.capnpc]
version = "0.27.0"
default-features = false

[workspace.dependencies.clap]
version = "4.6.7"
default-features = false

[workspace.dependencies.dialoguer]
version = "0.12.0"
default-features = false

[workspace.dependencies.dirs]
version = "7.0.0"
default-features = false

[workspace.dependencies.from-path]
version = "0.2.1"
default-features = false

[workspace.dependencies.futures]
version = "0.3.34"
default-features = false

[workspace.dependencies.jiff]
version = "0.2.38"
default-features = false

[workspace.dependencies.non-empty-iter]
version = "0.4.0"
default-features = false

[workspace.dependencies.non-empty-slice]
version = "0.7.0"
default-features = false

[workspace.dependencies.non-empty-str]
version = "0.13.0"
default-features = false

[workspace.dependencies.non-zero-size]
version = "0.2.0"
default-features = false

[workspace.dependencies.ownership]
version = "0.4.0"
default-features = false

[workspace.dependencies.reqwest]
version = "0.13.5"
default-features = false

[workspace.dependencies.serde]
version = "1.0.229"
default-features = false

[workspace.dependencies.serde_json]
version = "1.0.151"
default-features = false

[workspace.dependencies.thiserror]
version = "2.0.21"
default-features = false

[workspace.dependencies.tokio]
version = "1.53.2"
default-features = false

[workspace.dependencies.tracing]
version = "0.1.44"
default-features = false

[workspace.dependencies.tracing-subscriber]
version = "0.3.23"
default-features = false

[workspace.dependencies.trait-aliases]
version = "0.4.0"
default-features = false

[workspace.dependencies.url]
version = "2.5.8"
default-features = false

[workspace.dependencies.uuid]
version = "1.27.0"
default-features = false

[workspace.dependencies.jiyu-cli]
version = "0.1.0"
default-features = false
path = "crates/jiyu-cli"

[workspace.dependencies.jiyu-core]
version = "0.1.0"
default-features = false
path = "crates/jiyu-core"

[package]
name = "jiyu"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Freedom of managing proxies."
documentation = "https://docs.rs/jiyu"
repository.workspace = true
license.workspace = true
keywords = ["xray", "sing-box", "subscription", "proxy", "vpn"]
categories = ["command-line-utilities", "network-programming"]

[dependencies.jiyu-cli]
workspace = true

[dependencies.jiyu-core]
workspace = true
