[package]
name = "jiyu-schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Freedom of managing proxies. (schema)"
documentation = "https://docs.rs/jiyu-schema"
repository.workspace = true
license.workspace = true

[dependencies.bon]
workspace = true
features = ["std"]

[dependencies.capnp]
workspace = true
features = ["std", "alloc"]

[dependencies.serde]
workspace = true
features = ["std", "derive"]

[dependencies.ownership]
workspace = true
optional = true
features = ["std", "derive"]

[dependencies.thiserror]
workspace = true
features = ["std"]

[dependencies.jiyu-core]
workspace = true

[build-dependencies.capnpc]
workspace = true

[features]
default = ["ownership"]
ownership = ["dep:ownership", "jiyu-core/ownership"]
